MJEPersonalSettings = {
	autoFavor = false,
	favoredMounts = {},
	favoritePerChar = false,
	filter = {
		collected = true,
		color = {},
		expansion = {
			true,	-- [1]
			true,	-- [2]
			true,	-- [3]
			true,	-- [4]
			true,	-- [5]
			true,	-- [6]
			true,	-- [7]
			true,	-- [8]
			[0] = true,
		},
		faction = {
			alliance = true,
			horde = true,
			noFaction = true,
		},
		family = {
			Amphibian = {
				Crawgs = true,
				Toads = true,
			},
			Arachnids = {
				["Blood Ticks"] = true,
				Scorpions = true,
				Spiders = true,
			},
			Bats = true,
			Birds = {
				Albatross = true,
				Chickens = true,
				Cranes = true,
				Crows = true,
				["Dread Ravens"] = true,
				Hawkstriders = true,
				["Mechanical Birds"] = true,
				["Pandaren Phoenixes"] = true,
				Parrots = true,
				Phoenixes = true,
				Raptora = true,
				Roc = true,
				Tallstriders = true,
				Talonbirds = true,
				Vultures = true,
			},
			Bovids = {
				Clefthooves = true,
				Goats = true,
				Rams = true,
				Ruinstriders = true,
				Talbuks = true,
				Tauralus = true,
				Yaks = true,
			},
			Carnivorans = {
				Bears = true,
				Foxes = true,
				Gargon = true,
				Hounds = true,
				Hyenas = true,
				Quilen = true,
				Vulpin = true,
			},
			Cats = {
				Lions = true,
				Manasabers = true,
				["Mechanical Cats"] = true,
				Others = true,
				Sabers = true,
				["Stone Cats"] = true,
				Tigers = true,
			},
			Crabs = true,
			Demons = {
				["Demonic Hounds"] = true,
				["Demonic Steeds"] = true,
				Felsabers = true,
				Infernals = true,
				["Ur'zul"] = true,
			},
			Devourer = {
				Animite = true,
				Gorger = true,
				Mauler = true,
			},
			Dinosaurs = {
				Brutosaurs = true,
				Direhorns = true,
				Falcosaurs = true,
				Pterrordaxes = true,
				Raptors = true,
			},
			Dragonhawks = true,
			Drakes = {
				["Cloud Serpents"] = true,
				Drakes = true,
				["Grand Drakes"] = true,
				["Nether Drakes"] = true,
				Others = true,
				["Proto-Drakes"] = true,
				["Stone Drakes"] = true,
				["Undead Drakes"] = true,
				["Wind Drakes"] = true,
			},
			Elementals = {
				["Core Hounds"] = true,
				Others = true,
				Phoenixes = true,
				Sabers = true,
				["Stone Drakes"] = true,
				["Wind Drakes"] = true,
			},
			Feathermanes = {
				Gryphons = true,
				Hippogryphs = true,
				Larion = true,
				Wolfhawks = true,
				Wyverns = true,
			},
			Fish = {
				Fish = true,
				Seahorses = true,
				Stingrays = true,
			},
			Gargoyle = true,
			Horses = {
				Chargers = true,
				["Demonic Steeds"] = true,
				["Flying Steeds"] = true,
				["Horned Steeds"] = true,
				["Mechanical Steeds"] = true,
				["Mountain Horses"] = true,
				Steeds = true,
				["Undead Steeds"] = true,
			},
			Humanoids = {
				Gorger = true,
				Gronnlings = true,
				Yetis = true,
			},
			Insects = {
				Animite = true,
				["Aqir Flyers"] = true,
				Bees = true,
				Flies = true,
				Gorm = true,
				Krolusks = true,
				Moth = true,
				Ravagers = true,
				Silithids = true,
				Wasp = true,
				["Water Striders"] = true,
			},
			Jellyfish = true,
			Rats = true,
			Rays = {
				["Fathom Rays"] = true,
				["Mana Rays"] = true,
				["Nether Rays"] = true,
				Stingrays = true,
			},
			Razorwing = true,
			Reptiles = {
				Basilisks = true,
				Crocolisks = true,
				Kodos = true,
				Mushan = true,
				["N'Zoth Serpents"] = true,
				Others = true,
				["Sea Serpents"] = true,
				Shardhides = true,
				Snapdragons = true,
				Turtles = true,
			},
			Rylaks = true,
			Snail = true,
			Ungulates = {
				Alpacas = true,
				Boars = true,
				Camels = true,
				Cervid = true,
				Elekks = true,
				Mammoths = true,
				Moose = true,
				Ox = true,
				Rhinos = true,
				Riverbeasts = true,
				Runestag = true,
			},
			Vehicles = {
				Airplanes = true,
				Airships = true,
				["Assault Wagons"] = true,
				Book = true,
				Carpets = true,
				Discs = true,
				Gyrocopters = true,
				Hands = true,
				Hovercraft = true,
				["Jet Aerial Units"] = true,
				Kites = true,
				["Mecha-suits"] = true,
				["Mechanical Animals"] = true,
				Mechanostriders = true,
				Motorcycles = true,
				Rockets = true,
				Seat = true,
				["Spider Tanks"] = true,
			},
			Vombata = true,
			Wolves = {
				["Dire Wolves"] = true,
				Lupine = true,
				["Undead Wolves"] = true,
				["War Wolves"] = true,
				Wilderlings = true,
				Wolves = true,
			},
		},
		hidden = false,
		hiddenIngame = false,
		mountType = {
			flying = true,
			ground = true,
			passenger = true,
			repair = true,
			transform = true,
			underwater = true,
		},
		notCollected = true,
		onlyFavorites = false,
		onlyRecent = false,
		onlyTradable = false,
		onlyUsable = false,
		source = {
			Achievement = true,
			["Black Market"] = true,
			Class = true,
			Covenants = true,
			Drop = true,
			Garrison = true,
			Instance = true,
			["Island Expedition"] = true,
			PVP = true,
			Profession = true,
			Promotion = true,
			Quest = true,
			Reputation = true,
			Shop = true,
			Vendor = true,
			["World Event"] = true,
		},
	},
	hiddenMounts = {},
	personalFilter = false,
	personalHiddenMounts = false,
	personalUi = false,
	searchInDescription = true,
	sort = {
		by = "name",
		descending = false,
		favoritesOnTop = true,
		unownedOnBottom = true,
		unusableToBottom = false,
	},
	trackUsageStats = true,
	ui = {
		compactMountList = true,
		debugMode = false,
		enableCursorKeys = true,
		moveEquipmentSlot = true,
		previewButton = true,
		showAchievementPoints = true,
		showPersonalCount = true,
		showShopButton = false,
		showUsageStatistics = true,
		unlockDisplayCamera = true,
		windowSize = {
			0,	-- [1]
			0,	-- [2]
		},
	},
}
